### ISSUE TITLE
Bug: not waiting for Image placeholder => real image transition 

### ISSUE THREAD

**Issue by slorber** [argos-ci/argos-playwright#6]
## Bug description

Not sure what's the problem exactly or how it can be fixed.

I have a React image component that renders first a blurry placeholder, and it gets replaced by the real image after React hydrates.

For some reason, Argos doesn't seem to wait for the placeholder to be replaced by the real image tag, and this can lead to screenshots being taken too early

### Correct behavior expected

screenshot the real image once loaded

### Wrong behavior observed

screenshot the blurry placeholder

### Screenshot

https://app.argos-ci.com/slorber/docusaurus-visual-tests/builds/10/40206532

![CleanShot 2023-03-03 at 19 02 22@2x](https://user-images.githubusercontent.com/749374/222794390-430c5f99-8dc2-4136-93e4-555dbb7c9dca.png)

## Reproduce

Try to screenshot this page: https://docusaurus.io/docs/playground

Sometimes it leads to a blurry placeholder

## Setup

Describe the setup you have when you encounter the bug : device, browser, library version...

## Additional information

The code used to switch from the blurry placeholder to the real image is here:
https://github.com/endiliey/react-ideal-image/blob/master/src/components/IdealImage/index.js

It's quite old, and it is probably the fault of this code, not Argos, but still wanted to open the discussion because you may have encountered this issue before. 

Was wondering for example if Argos would:
- wait for React hydration?
- try to fit all the content in current viewport, making sure that libs detecting viewport entrance (like react-waypoint here) have time to trigger their `onEnter` events)

---

The rendered markup switches from:

```html 
<a href="https://docusaurus.new/stackblitz" target="_blank" rel="noopener noreferrer">
   <div style="background-size:cover;background-repeat:no-repeat;position:relative;background-image:url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAGCAYAAAD68A/GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAA2UlEQVR4nB2OzU7CQAAG9wEMQgCp7Xa73daWJaBoTHxLPBBPpPEh/ImJZ8NZPVouuARjFE89GBLHlEkm8x0/Ya3l7PyC4WiMNunOKE7wwwipNEobVGQQMspQxuIFMb5K6XqKrH/M/eMDT/M5zy+v3NzeIXqBwY+H9MKcejc7AUf2hOXyHedW8Acf6zXiUCaEyQip+0id0/Y0mT2lXCxwzvG73fJWlogwztDJgPqCJ1NaHUk+GLPZ/FBVFTWf31+I/dYBtY1md9e9RhtfaqbTK2azgqK4ZjK55B8ECXu6qQVRyQAAAABJRU5ErkJggg==&quot;)">
      <svg style="width:100%;height:auto;max-width:100%;margin-bottom:-4px" width="640" height="356"></svg>
      <noscript><img style="width:100%;height:auto;max-width:100%;margin-bottom:-4px;position:absolute;top:0;left:0" src="https://d33wubrfki0l68.cloudfront.net/664f5db095eb34e875e932eb1cce0b286906cfb2/9f1c2/assets/ideal-img/stackblitz.da95b77.640.png" srcset="https://d33wubrfki0l68.cloudfront.net/664f5db095eb34e875e932eb1cce0b286906cfb2/9f1c2/assets/ideal-img/stackblitz.da95b77.640.png 640w,https://d33wubrfki0l68.cloudfront.net/4594d2cadb54291a90ce849a10cd579a94b37029/eab63/assets/ideal-img/stackblitz.ab6e191.1030.png 1030w" alt="⚡ StackBlitz 🆕's image" width="640" height="356"></noscript>
   </div>
</a>
```

To:

```html 
<a href="https://docusaurus.new/stackblitz" target="_blank" rel="noopener noreferrer">
   <div style="background-size: cover; background-repeat: no-repeat; position: relative;"><img src="/assets/ideal-img/stackblitz.ab6e191.1030.png" alt="⚡ StackBlitz 🆕's image" width="640" height="356" style="width: 100%; height: auto; max-width: 100%; margin-bottom: -4px;"></div>
</a>
```

**Comment by gregberge** [comment]
Hi @slorber, in term of accessibility, these blurry image placeholder should use [`aria-busy` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-busy) isn't it?

If you do so, it will be automatically awaited by Argos.

**Comment by gregberge** [comment]
@slorber ? any update?

**Comment by slorber** [comment]
Didn't have time to investigate sorry 😅 probably my fault so going to close and see if I can create a smaller repro
